config/routes.rb
Ewd::Application.routes.draw do
  resources :beta_users do
    collection do
      get :csv
    end
  end

  root :to => "home#index"

end

app/models/beta_user.rb
class BetaUser < ActiveRecord::Base
  validates_presence_of :name, :email, :wedding_date, :wedding_city, :wedding_state

  BOM = "\377\376" #Byte Order Mark
  
  def self.to_csv
    "Name,Email,Date,City,State\r#{BetaUser.all.map { |b| "#{b.name},#{b.email},#{b.wedding_date},#{b.wedding_city},#{b.wedding_state}"}.join("\r")}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beta_users_controller.rb
require 'iconv'
class BetaUsersController < ApplicationController
  def create
    @beta_user = BetaUser.new(params[:beta_user])
    if !@beta_user.save
      render :action => "new"
    end
  end

  def new
    @beta_user = BetaUser.new
  end

  def csv
    filename = "ewd_users.csv"
    content = BetaUser.to_csv
#    content = BetaUser::BOM + Iconv.conv("utf-16le", "utf-8", content)
    send_data content, :filename => filename
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beta_users_helper.rb
module BetaUsersHelper
end

app/views/beta_users/create.html.haml
.signup
  %h2 Success!
  %p
    Please check your email in the coming
    days/weeks for exclusive offers
    %br
    as they become available.

app/views/beta_users/new.html.haml
:javascript
  $(function() {
    window.initializeGoogleMaps = function() {};

    function loadScript() {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src = "http://maps.google.com/maps/api/js?sensor=false&callback=initializeGoogleMaps";
      document.body.appendChild(script);
    }

    loadScript();

    $("#signup_button").click(function() {
      $(this).html("");
      $(this).append($("#loading"));

      var form = $(this).closest('form');
      
      var cityAndState = $("#beta_user_wedding_city").val() + ", " + $("#beta_user_wedding_state").val();

      var geocoder = new google.maps.Geocoder();
      geocoder.geocode({address: cityAndState}, function(results) {
      window.georesults = results;
        var result = results[0];

        if (result) {
          $("#beta_user_wedding_lat").val(result.geometry.location.lat());
          $("#beta_user_wedding_lng").val(result.geometry.location.lng());
        }
        form.submit()
      });
    })
  })

.signup
  %h3 Exclusive Wedding Deals Membership
  %p
    Sign up to receive exclusive
    %br 
    wedding deals from top vendors.
  = form_for @beta_user do |f|
    - if @beta_user.errors.any?
      .errors
        %h4 There was a problem saving your registration.
        %ul
          - @beta_user.errors.full_messages.each do |msg|
            %li= msg

    %p
      = f.label :name
      = f.text_field :name
    %p
      = f.label :email
      = f.text_field :email
    %p
      = f.label :wedding_date, "Wedding Date"
      = f.text_field :wedding_date
    %p
      = f.label :wedding_city, "Wedding City"
      = f.text_field :wedding_city, :style => "width: 10em"
      &nbsp;
      = f.label :wedding_state, "State"
      = f.text_field :wedding_state, :size => 2
    = f.hidden_field :wedding_lat
    = f.hidden_field :wedding_lng
    %p
      = link_to_function("Sign Up", :class => "fancy button", :id => "signup_button")
    .hidden
      = image_tag("ajax-loader.gif", :id => "loading")

app/views/home/index.html.haml
.signup
  %h2
    %span.fancy Exclusive
    Wedding Deals
  %p
    Insider discounts from top
    %br
    wedding professionals.
  = link_to("Sign Up", new_beta_user_path, :class => "fancy button")

#background-cache
  - 7.times do |i|
    = image_tag("background_photos/bg#{i+1}.jpg", :title => "", :onload => "queueBackgroundImage(this)")

app/views/layouts/_analytics.html.haml
<script type="text/javascript">

var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-52439-11']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();

</script>

app/views/layouts/_footer.html.haml
.footer
  .containing.smallish
    .copyright
      &copy; WeddingMapper 2011
    = link_to("Contact", "http://www.weddingmapper.com/about/contact", :target => "_blank")

app/views/layouts/_header.html.haml
.header
  .containing
    .brought_by.smallish
      = link_to(image_tag("wedding_mapper_logo_icon.png"), "http://www.weddingmapper.com", :target => "_blank", :class => "wm_logo")
      .wm_text
        = link_to("Brought to you by", "http://www.weddingmapper.com", :target => "_blank")
        %br
        = link_to("WeddingMapper.com", "http://www.weddingmapper.com", :target => "_blank")
        
    = link_to(image_tag("logo.png"), root_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Exclusive Wedding Deals
    = stylesheet_link_tag "site"
    = javascript_include_tag "jquery-1.5.1.min", "rails"
    = csrf_meta_tag
    %link{:href => 'http://fonts.googleapis.com/css?family=Quattrocento&v1', :rel => 'stylesheet', :type => 'text/css'}
    %link{:href => 'http://fonts.googleapis.com/css?family=Tangerine&v1', :rel => 'stylesheet', :type => 'text/css'}

  %body
    = render "layouts/header"
    #content_container
      #content.content
        = image_tag("background_photos/bg#{rand(7) + 1}.jpg", :title => "", :class => "background_image")
        .containing= yield
      = render "layouts/footer"

    = render "layouts/analytics"